"""Canonical model capability/metadata domain."""

from models.metadata.capabilities import (
    CapabilitySource,
    CapabilitySources,
    resolve_model_metadata,
    resolve_supports_vision,
)
from models.metadata.interpretation import (
    UNKNOWN_MODEL_BASE,
    builtin_model_metadata,
    dict_or_empty,
    entry_supports_vision,
    extract_context,
    extract_limit,
    merge_catalog_entry_with_override,
    model_info_from_entry,
    model_metadata_from_entry,
    model_metadata_patch_from_entry,
    override_int,
    override_to_catalog_shape,
    provider_info_from_entry,
    vision_marker_metadata,
)
from models.metadata.reasoning import (
    configure_reasoning_metadata_sources,
    nous_catalog_url,
    nous_model_reasoning_capabilities,
    openrouter_model_reasoning_capabilities,
    parse_openrouter_reasoning_capabilities,
    refresh_reasoning_caps_async,
    warm_nous_reasoning_caps_async,
    warm_openrouter_reasoning_caps_async,
)
from models.metadata.types import (
    ModelInfo,
    ModelMetadata,
    ModelMetadataContext,
    ModelMetadataPatch,
    ProviderInfo,
    ReasoningMetadata,
)

__all__ = [
    "CapabilitySource",
    "CapabilitySources",
    "ModelInfo",
    "ModelMetadata",
    "ModelMetadataContext",
    "ModelMetadataPatch",
    "ProviderInfo",
    "ReasoningMetadata",
    "UNKNOWN_MODEL_BASE",
    "builtin_model_metadata",
    "configure_reasoning_metadata_sources",
    "dict_or_empty",
    "entry_supports_vision",
    "extract_context",
    "extract_limit",
    "merge_catalog_entry_with_override",
    "model_info_from_entry",
    "model_metadata_from_entry",
    "model_metadata_patch_from_entry",
    "nous_catalog_url",
    "nous_model_reasoning_capabilities",
    "openrouter_model_reasoning_capabilities",
    "override_int",
    "override_to_catalog_shape",
    "parse_openrouter_reasoning_capabilities",
    "provider_info_from_entry",
    "refresh_reasoning_caps_async",
    "resolve_model_metadata",
    "resolve_supports_vision",
    "vision_marker_metadata",
    "warm_nous_reasoning_caps_async",
    "warm_openrouter_reasoning_caps_async",
]
